name: End-to-end tests

on: push

jobs:
    cypress-run:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Cypress run
              uses: cypress-io/github-action@v6
              with:
                  record: true
              env: # Ensure environment variables are within the correct step
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Upload screenshots on failure
              uses: actions/upload-artifact@v4
              if: failure() # Conditional to only run this step if previous steps fail
              with:
                  name: cypress-screenshots
                  path: cypress/screenshots
                  if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`

            - name: Upload videos on failure
              uses: actions/upload-artifact@v4
              with:
                  name: cypress-videos
                  path: cypress/videos
                  if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
